---
title: "Class1 April12"
author: "Markus Loecher"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("nycflights13")
library(nycflights13)

# data source: NY Times, https://tinyurl.com/t9j9fdw
# https://github.com/nytimes/covid-19-data

# create an object called nyt_st_url that contains the url
nyt_st_url <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"
nyt_st <- read.csv(nyt_st_url, stringsAsFactors = FALSE)



getwd()
2 + 2
sqrt(9)
3^2
3*3
getwd()
2 - 2
x=2
y=2
x+y
x
x <- 2
x == 2
x = c(2,3,4)
y = c(4,3,2)
x+y
x^2
x = 2:4
2:4
seq(2,4,1)
seq(2,8,2)
seq(from=2,to=8,by=2)
?seq
seq(from=2,to=8, length=4)
seq(from=2,to=8, length=8)

# Boolean Logicx = 2:4
x = c(2,3,4)
seq(from=2,to=8, len=7)
seq(from=2,to=8, length=7)
x = c(2,3,4,5)
x+y
x[2]
x[4]
x[3:4]
x[c(1,4)]
x[-2]
x[-c(1,4)]
x[5]
1:100
sum(1:100)
101 * 50
sum(1:1000)
n=200
n*(n+1)/2
sum(1:n)
mean(1:n)
x
x = 1:100
x
x = (1:20)^2
x
clear
clear()
x[13]
x[13:15]
x[-(1:5)]
x[c(1,4)]
x[-c(1,4)]
2 = 3
2 == 3
2^2 == 4

x < 16
# Boolean Subsetting
x[x<16]
! x < 16
x[! x<16]
!x < 16
!x<16
print(x[-x<16])

# My first plot:
x = (1:20)
y = x^2

plot(x, pch = 1:20)

plot(x,y)
par(bg="white")
plot(x,y, col ="darkblue", pch = 20);grid()
title("My first plot in R")

barplot(y, xlab = "x", ylab="y")
axis(1)

####### Matrices ########

x = matrix(1:9, ncol=3)
colnames(x) = c("Paris", "Madrid", "Copenhagen")
rownames(x) = c("2018", "2019", "2020")

x[2,2] 
x["2019", "Madrid"]
x[-2,2]
x[-"2019", "Madrid"]

sum(x)
rowSums(x)
colSums(x)
rowMeans(x)
colMeans(x)
x[2,2] <- NA
colSums(x, na.rm = TRUE)/3

colMeans(x, na.rm = TRUE)

# Matrices allow only one data type for all columns!!

# Data frames are like matrices but allow for different types.

x = data.frame(a = 1:3, l = LETTERS[1:3], d = as.Date("2020-10-05") + 1:3)
x[2,2]
dim(x)

class(as.Date("2020-10-05"))

as.Date("2020-10-05") + 1:3
"2020-10-05" + 1

#3 ways to select a clolumn:
x[,3]
x[,"d"]
x$d # only for data frames and lists !

# Introduction to Statistical Learning (ISLR)

library(ISLR)
data(Auto)
View(Auto)

#### lists ####

x = list()

# method 1
x$a = 1:3
x$b = c("ATL", "CGN", "LHR", "TXL")
x$c = matrix(1:9, ncol =3)
```

