---
title: "homework 04/26/21"
author: "Themenfeld SS 2021"
date: "04/26/21"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nycflights13)
library(dplyr)
data(flights)
# get rid of tibble type
flights = as.data.frame(flights)
```

1. Compute the 90% quantile of `arr_delay`
```{r}
quantile(flights$arr_delay, na.rm = TRUE, probs = 0.9)
```

2. Compute the 90% quantile of `arr_delay` grouped by `origin`
```{r}
by_origin <- group_by(flights, origin)
my_quantile <- summarise(by_origin, m = quantile(arr_delay, probs = 0.9, na.rm = TRUE))
#group_by(flights, origin) %>% summarise( m = quantile(arr_delay, p =0.9, na.rm=TRUE))

#by_origin <- group_by(lateArrivals, origin)

#my_quantile <- summarize(by_origin,
#                       quantile = quantile(lateArrivals$arr_delay, probs = 0.9, na.rm = TRUE))

my_quantile
```

3. Create a (default) histogram of `arr_delay` and extract the **density** value for the 10th bar.
```{r}
# method1:
my_arr_del_hist <- hist(flights$arr_delay)
my_arr_del_hist$density[10]

kn1 = 1
kn2 = 1
for (i in 1:10) {
  kn = kn1+ kn2
  print(kn)
  kn2 = kn1
  kn1 = kn
}

# method2 for loop:
for (o in unique(flights$origin)) {
  x = subset(flights, origin == o)
  print(quantile(x$arr_delay, p=0.9, na.rm=TRUE))
}

## the pipe operator `%>%`
group_by(flights, origin) %>% summarise( m = quantile(arr_delay, p =0.9, na.rm=TRUE))
```