---
title: "String Manipulation Challenge"
author: "Sebastian Knoche"
date: "05/04/2021"
output: github_document
---

Write a function that reverses the order of the words of the input sentence.
```{r echo=FALSE}
# generate the sample string
my.sentence <- "here is long sentence, potentially generated by reading from some text-file"

# function parameter is the string to be split and then reversed.
# by default this is done word for word (any_split=" "),
# to reverse the string by character, any_split="" can be used.

my.wordSeqReverse <- function(any_sentence, any_split=" ", return_as_list=FALSE){

  rev_word_seq <- rev(
    unlist(strsplit(any_sentence, split = any_split)))
  ifelse(return_as_list, return(list(rev_word_seq)), return(paste(rev_word_seq, sep = " ")))
}
```

```{r}
my.sentence
my.wordSeqReverse(my.sentence)
```

Now we want a function that keeps the order of the sentence, but
reverses the words!
```{r echo=FALSE}
my.sentence <- "here is long sentence, potentially generated by reading from some text-file"
my.strReverse <- function(any_sentence){
  tmp_str <- unlist(strsplit(any_sentence, split = " "))
  rev_str <- my.wordSeqReverse(tmp_str, any_split = "", return_as_list=TRUE)
  return(rev_str)
}
```

```{r}
my.strReverse(my.sentence)
```


```{r echo=FALSE}
# Yilun's code
my.strReverse = function(inputString){
  #Split it into single word
  words=unlist(strsplit(inputString,split = " "))
  #For each Word
  for(i in seq_along(words)) {
    #reaplace with reversed order
    words[i] = paste0(
      rev(
        unlist(
          strsplit(
            words[i],
            split = ""
            )
          )
        ),
      collapse = ""
    )
    }
  #create sentence
  paste0(words,collapse = " ")
}
```
```{r echo=FALSE}
# mick's code
remove.vowel = function(string){
  fstring = unlist(
    strsplit(
      string, split = " "
      )
    )
  ffstring = unlist(
    strsplit(
      fstring, split = ""
      )
    )
  for(i in seq_along(ffstring)){
    is.vowel <- function(char){
      if(char == "a" || char == "e" || char == "i" || char == "o" || char == "u")
        remove(ffstring[i])
      }
    }
  paste0(ffstring, collapse = " ")
  }
remove.vowel(my.sentence2) 
```